name: AppCenter Build and Deploy

on:
  push:
    branches:
      - 'main' # "feature/" ile başlayan tüm branch'ler için çalışır.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

          
      - name: Build and Deploy to AppCenter
        run: |
          # AppCenter'a yükleme komutlarını burada çalıştırın.
          # Örneğin:
          appcenter login --token 5924f27c13f242f8cc58cd5c8b0438ba8a4ca874
          appcenter apps list
